Adds a community folder with a Hacktoberfest page therein.
redis-stack/redis-stack-docs pull request #82
Opened 2022-09-23 22:43 UTC by SuzeShardlow

2022-09-23 23:02 UTC, SuzeShardlow commented
Hi @banker and @itamarhaber, please review and merge this PR as discussed.

Unfortunately, I can't test it on my machine (the instructions in the README don't work for me) / have a Netlify preview link generated (because I need a maintainer to approve the workflow first).  Thanks!

2022-09-30 00:14 UTC, banker requested changes
Looking good!

One request is that we make this into a generic Hacktoberfest page that can be reused in subsequent years. So, I'd suggest we rename the page to "hacktoberfest.md". We can update the page yearly as needed and provide information about our previous Hactoberfest participation, etc.

2022-09-30 00:14 UTC, banker commented on community/hacktoberfest_2022.md
> +Through October, we're creating a number of GitHub issues for folks who want to contribute to our documentation and demo apps. [View our list of current open issues](https://github.com/search?l=&q=%2
```suggestion
Through October, we at Redis are creating a number of GitHub issues for folks who want to contribute to our documentation and demo apps. [View our list of current open issues](https://github.com/search?l=&q=%23hacktoberfest+user%3Aredislabs-training+user%3Aredis+user%3Aredis-developer+user%3ANodeRedis+label%3Ahacktoberfest&state=open&type=Issues).
```

2022-09-30 00:14 UTC, banker commented on community/hacktoberfest_2022.md
> +Through October, we're creating a number of GitHub issues for folks who want to contribute to our documentation and demo apps. [View our list of current open issues](https://github.com/search?l=&q=%2
I was able to get the link to produce issues by removing the #hacktoberfest hash tag: https://github.com/search?q=user%3Aredislabs-training+user%3Aredis+user%3Aredis-developer+user%3ANodeRedis+label%3Ahacktoberfest&type=Issues

Do we want to update this?

2022-10-01 22:25 UTC, banker approved these changes

2022-10-01 22:25 UTC, merged